---
steps:
  build:
    image: rust:1.76
    commands:
      - cargo build --release
  publish:
    image: clearlinux:base
    commands:
      - mkdir -p ./target/docker
      - cp ./target/release/klt ./target/docker/klt
      - ./target/docker/klt recipe.toml
      - ./target/docker/klt recipe-clear.toml
    secrets: [gitea_token]
