[base]
registry = "gcr.io"
repo = "distroless/cc-debian12"
tag = "latest"

[target]
registry = "git.jmteegen.eu"
repo = "max/komainu"
tag = "hacky"
auth = "$DOCKER_PASSWORD"

[modification]
app_layer_folder = "/tmp/komainu"

[modification.execution_config]
cmd = ["/komainu"]
user = "1000:1000"
working_dir = "/"
exposed_ports = ["3000/tcp"]
