[base]
registry = "gcr.io"
repo = "distroless/cc-debian12"
tag = "latest"

[target]
registry = "git.jmteegen.eu"
repo = "max/kleinladungstraeger"
tags = ["latest", "distroless"]
auth = "$GITEA_TOKEN"

[modification]
app_layer_folder = "target/docker"

[modification.execution_config]
Cmd = ["/klt"]
