[base]
image = "registry-1.docker.io/library/clearlinux:base"

[target]
registry = "ghcr.io"
repo = "max-te/kleinladungstraeger"
tags = ["clear"]
auth = ["max-te", "$GITHUB_TOKEN"]

[modification]
app_layer_folder = "target/docker"

[modification.execution_config]
Cmd = ["klt"]

[modification.execution_config.Labels]
"org.opencontainers.image.source" = "https://github.com/max-te/kleinladungstraeger"

[modification.annotations]
"org.opencontainers.image.source" = "https://github.com/max-te/kleinladungstraeger"
