[base]
image = "gcr.io/distroless/cc-debian12:latest"

[target]
registry = "ghcr.io"
repo = "max-te/kleinladungstraeger"
tags = ["latest", "distroless"]
auth = ["max-te", "$GITHUB_TOKEN"]

[modification]
app_layer_folder = "target/docker"

[modification.execution_config]
Cmd = ["/bin/klt"]

[modification.execution_config.Labels]
"org.opencontainers.image.source" = "https://github.com/max-te/kleinladungstraeger"

[modification.annotations]
"org.opencontainers.image.source" = "https://github.com/max-te/kleinladungstraeger"
