[base]
registry = "registry-1.docker.io"
repo = "library/clearlinux"
tag = "base"

[target]
registry = "ghcr.io"
repo = "max-te/kleinladungstraeger"
tag = "clear"
auth = ["max-te", "$GITHUB_TOKEN"]

[modification]
app_layer_folder = "target/docker"

[modification.execution_config]
Cmd = ["/bin/klt"]

[modification.execution_config.Labels]
"org.opencontainers.image.source" = "https://github.com/max-te/kleinladungstraeger"
