[base]
image = "registry-1.docker.io/library/clearlinux:base"

[target]
registry = "ghcr.io"
repo = "$GITHUB_REPOSITORY"
tags = ["clear", "$RELEASE_TAG-clear"]
auth = ["$GITHUB_ACTOR", "$GITHUB_TOKEN"]

[modification]
app_layer_folder = "target/docker"

[modification.execution_config]
Cmd = ["klt"]

[modification.execution_config.Labels]
"org.opencontainers.image.source" = "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"

[modification.annotations]
"org.opencontainers.image.source" = "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
